[package]
name = "cassie_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassie_event = {path="../cassie_event"}
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"